export const events = [
  {
    id: "max-dean-throwdown-ldn",
    name: "Max Dean Throwdown LDN",
    date: "23 September 2026",
    location: "LDN EAST, Canning Town, London",
    category: "Event",
    latitude: 51.51721,
    longitude: 0.00419,
  },
  {
    id: "creamfields-bronze-camping",
    name: "4 Day Bronze Camping – Creamfields",
    date: "27 August 2026 – 30 August 2026",
    location: "Creamfields, Daresbury, Cheshire",
    category: "Festival",
    latitude: 53.34709,
    longitude: -2.61833,
  },
  {
    id: "creamfields-silver-camping",
    name: "4 Day Silver Camping – Creamfields",
    date: "27 August 2026 – 30 August 2026",
    location: "Creamfields, Daresbury, Cheshire",
    category: "Festival",
    latitude: 53.34709,
    longitude: -2.61833,
  },
  {
    id: "creamfields-gold-camping",
    name: "4 Day Gold Camping – Creamfields",
    date: "27 August 2026 – 30 August 2026",
    location: "Creamfields, Daresbury, Cheshire",
    category: "Festival",
    latitude: 53.34709,
    longitude: -2.61833,
  },
  {
    id: "anotr-alexandra-palace",
    name: "ANOTR",
    date: "18 September 2026",
    location: "Alexandra Palace, London",
    category: "Event",
    latitude: 51.5948,
    longitude: -0.1275,
  },
  {
    id: "fumiya-tanaka-manchester",
    name: "Fumiya Tanaka",
    date: "26 September 2026",
    location: "The Loft, Manchester",
    category: "Event",
    latitude: 53.4958,
    longitude: -2.2115,
  },
  {
    id: "you-and-me-friday",
    name: "You&Me (Friday)",
    date: "2 October 2026",
    location: "Depot Mayfield, Manchester",
    category: "Event",
    latitude: 53.4756,
    longitude: -2.2282,
  },
  {
    id: "you-and-me-saturday",
    name: "You&Me (Saturday)",
    date: "3 October 2026",
    location: "Depot Mayfield, Manchester",
    category: "Event",
    latitude: 53.4756,
    longitude: -2.2282,
  },
  {
    id: "uss-friday",
    name: "USS (Friday)",
    date: "9 October 2026",
    location: "Aviva Studios, Manchester",
    category: "Event",
    latitude: 53.47819,
    longitude: -2.25773,
  },
  {
    id: "uss-saturday",
    name: "USS (Saturday)",
    date: "10 October 2026",
    location: "Aviva Studios, Manchester",
    category: "Event",
    latitude: 53.47819,
    longitude: -2.25773,
  },
  {
    id: "rossi-blackstone-liverpool",
    name: "Rossi",
    date: "10 October 2026",
    location: "Blackstone Street Warehouse, Liverpool",
    category: "Event",
    latitude: 53.4185,
    longitude: -3.0037,
  },
  {
    id: "elrow-horroween",
    name: "Elrow Horroween",
    date: "31 October 2026",
    location: "Drumsheds, London",
    category: "Event",
    latitude: 51.6081,
    longitude: -0.04686,
  },
  {
    id: "chris-stussy-bristol",
    name: "Chris Stussy",
    date: "7 November 2026",
    location: "The Prospect Building, Bristol",
    category: "Event",
    latitude: 51.44863,
    longitude: -2.57359,
  },
  {
    id: "chris-stussy-liverpool",
    name: "Chris Stussy",
    date: "21 November 2026",
    location: "Blackstone Street Warehouse, Liverpool",
    category: "Event",
    latitude: 53.4185,
    longitude: -3.0037,
  },
  {
    id: "max-dean-we-are-whse",
    name: "Max Dean We Are WHSE",
    date: "26 December 2026",
    location: "Ultra Warehouse, Derby",
    category: "Event",
    latitude: 52.92051,
    longitude: -1.44958,
  },
];